import { Schema, model, Types } from 'mongoose';

export interface TransactionDocument {
    _id: Types.ObjectId;
    tenantId: Types.ObjectId;
    studentId: Types.ObjectId;
    reference: string; // Unique reference generated by us (TRX-...)
    externalId?: string; // ID from Wompi/Stripe
    amount: number;
    currency: string;
    status: 'PENDING' | 'APPROVED' | 'DECLINED' | 'VOIDED' | 'ERROR';
    gateway: 'WOMPI' | 'STRIPE';
    metadata?: any; // To store raw response/webhook data
    createdAt: Date;
    updatedAt: Date;
}

const TransactionSchema = new Schema<TransactionDocument>(
    {
        tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
        studentId: { type: Schema.Types.ObjectId, ref: 'Student', required: true, index: true },
        reference: { type: String, required: true, unique: true, index: true },
        externalId: { type: String, sparse: true, index: true },
        amount: { type: Number, required: true },
        currency: { type: String, required: true, default: 'COP' },
        status: {
            type: String,
            enum: ['PENDING', 'APPROVED', 'DECLINED', 'VOIDED', 'ERROR'],
            default: 'PENDING',
            index: true,
        },
        gateway: { type: String, enum: ['WOMPI', 'STRIPE'], required: true },
        metadata: { type: Schema.Types.Mixed },
    },
    { timestamps: true },
);

// Indexes
TransactionSchema.index({ tenantId: 1, createdAt: -1 });

export const TransactionModel = model<TransactionDocument>('Transaction', TransactionSchema);
